version: '3.8'

services:
  solidityscan-mcp:
    image: 132830644905.dkr.ecr.us-east-2.amazonaws.com/solidityscan-mcp-server:latest
    ports:
      - target: 8080
        published: 9090
        protocol: tcp
        mode: host
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - NODE_ENV=production
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == worker
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - solidityscan-network

networks:
  solidityscan-network:
    driver: overlay

