export const platformChainData = {
  data: {
    xdc: { id: "12", chains: [{ mainnet: "1" }, { testnet: "2" }] },
    celo: { id: "7", chains: [{ mainnet: "1" }, { testnet: "2" }] },
    fuse: { id: "15", chains: [{ mainnet: "1" }, { testnet: "2" }] },
    opbnb: { id: "24", chains: [{ mainnet: "1" }, { testnet: "2" }] },
    aurora: { id: "8", chains: [{ mainnet: "1" }, { testnet: "2" }] },
    cronos: { id: "6", chains: [{ mainnet: "1" }, { testnet: "2" }] },
    fantom: { id: "5", chains: [{ mainnet: "1" }, { testnet: "2" }] },
    bscscan: {
      id: "2",
      chains: [{ mainnet: "1" }, { testnet: "2" }],
    },
    subscan: {
      id: "23",
      chains: [
        { "peaq-mainnet": "7" },
        { "agung-testnet": "9" },
        { "astar-mainnet": "1" },
        { "krest-mainnet": "8" },
        { "darwinia-mainnet": "10" },
        { "moonbase-testnet": "6" },
        { "moonbeam-mainnet": "4" },
        { "polkadot-mainnet": "11" },
        { "moonriver-mainnet": "5" },
        { "astar-shiden-mainnet": "2" },
        { "astar-shibuya-testnet": "3" },
      ],
    },
    thirdfy: {
      id: "20",
      chains: [{ mainnet: "1" }, { testnet: "2" }],
    },
    arbiscan: {
      id: "9",
      chains: [{ nova: "7" }, { goerli: "3" }, { mainnet: "1" }, { sepolia: "4" }],
    },
    basescan: {
      id: "17",
      chains: [{ mainnet: "1" }, { testnet: "2" }],
    },
    optimism: {
      id: "11",
      chains: [{ goerli: "3" }, { mainnet: "1" }],
    },
    reefscan: {
      id: "13",
      chains: [{ mainnet: "1" }, { testnet: "2" }],
    },
    tronscan: {
      id: "19",
      chains: [{ nile: "9" }, { shasta: "8" }, { mainnet: "1" }],
    },
    avalanche: {
      id: "4",
      chains: [{ mainnet: "1" }, { testnet: "2" }],
    },
    buildbear: { id: "10", chains: [{ buildbear: null }] },
    etherscan: {
      id: "1",
      chains: [{ holesky: "6" }, { mainnet: "1" }, { ropsten: "5" }, { sepolia: "4" }],
    },
    firechain: {
      id: "22",
      chains: [{ mainnet: "1" }, { testnet: "2" }],
    },
    lineascan: {
      id: "21",
      chains: [{ mainnet: "1" }, { sepolia: "4" }],
    },
    routescan: {
      id: "18",
      chains: [{ boba: "1" }, { flare: "2" }, { metis: "3" }, { chiliz: "4" }, { "c-chain": "5" }],
    },
    sonicscan: {
      id: "25",
      chains: [{ mainnet: "1" }, { testnet: "2" }],
    },
    blockscout: {
      id: "16",
      chains: [
        { etc: "1" },
        { eth: "3" },
        { base: "7" },
        { neon: "10" },
        { gnosis: "12" },
        { optimism: "14" },
        { rootstock: "17" },
        { "etc-mordor": "2" },
        { "eth-goerli": "4" },
        { "base-goerli": "8" },
        { "eth-holesky": "6" },
        { "eth-sepolia": "5" },
        { "neon-devnet": "11" },
        { "base-sepolia": "9" },
        { "fuse-mainnet": "20" },
        { "fuse-testnet": "21" },
        { "hemi-testnet": "77" },
        { "lisk-testnet": "47" },
        { "omni-testnet": "54" },
        { "reya-mainnet": "48" },
        { "astar-mainnet": "40" },
        { "gnosis-chiado": "13" },
        { "lukso-mainnet": "53" },
        { "verify-testnet": "52" },
        { "zksync-mainnet": "62" },
        { "zksync-testnet": "63" },
        { "optimism-goerli": "15" },
        { "shimmer-mainnet": "22" },
        { "shimmer-testnet": "23" },
        { "soneium-mainnet": "78" },
        { "iota-evm-mainnet": "38" },
        { "iota-evm-testnet": "39" },
        { "optimism-sepolia": "16" },
        { "redstone-mainnet": "58" },
        { "blackfort-mainnet": "55" },
        { "blackfort-testnet": "56" },
        { "etherlink-mainnet": "74" },
        { "etherlink-testnet": "75" },
        { "immutable-mainnet": "29" },
        { "immutable-testnet": "18" },
        { "lightlink-mainnet": "24" },
        { "lightlink-testnet": "25" },
        { "lineascan-testnet": "64" },
        { "rootstock-testnet": "28" },
        { "stability-mainnet": "36" },
        { "stability-testnet": "37" },
        { "zetachain-mainnet": "30" },
        { "zetachain-testnet": "31" },
        { "assetchain-mainnet": "70" },
        { "assetchain-testnet": "69" },
        { "caminoscan-mainnet": "72" },
        { "caminoscan-testnet": "73" },
        { "creditcoin-testnet": "35" },
        { "zksync-era-mainnet": "19" },
        { "astar-zkevm-mainnet": "44" },
        { "reya-cronos-testnet": "49" },
        { "arbitrum-one-mainnet": "57" },
        { "astar-shiden-testnet": "42" },
        { "astar-zkyoto-testnet": "43" },
        { "celo-baklava-testnet": "33" },
        { "astar-shibuya-testnet": "41" },
        { "oneworldchain-mainnet": "80" },
        { "polygon-zkevm-mainnet": "34" },
        { "shibariumscan-mainnet": "26" },
        { "shibariumscan-testnet": "27" },
        { "tangible-real-mainnet": "46" },
        { "celo-alfajores-testnet": "32" },
        { "japanopenchain-mainnet": "71" },
        { "japanopenchain-testnet": "76" },
        { "soneium-minato-testnet": "79" },
        { "anomaly-sepolia-testnet": "61" },
        { "connext-sepolia-testnet": "60" },
        { "redstone-garnet-testnet": "59" },
        { "tangible-unreal-testnet": "45" },
        { "lineascan-goerli-testnet": "65" },
        { "lineascan-sepolia-testnet": "66" },
        { "playance-playblock-mainnet": "51" },
      ],
    },
    nordekscan: {
      id: "14",
      chains: [{ mainnet: "1" }, { testnet: "2" }],
    },
    polygonscan: {
      id: "3",
      chains: [
        { mainnet: "1" },
        { testnet: "2" },
        { "amoy-testnet": "10" },
        { "cardona-testnet": "11" },
      ],
    },
  },
} as const;


